### ISSUE TITLE
request for drought_variable_pentads.csv 

### ISSUE THREAD

**Issue by remarkSD** [anniebritton/Eco-Drought-South-Dakota#1]
Hi, 

I was trying to replicate your work including the data processing. I would just like to request if you could also provide the data you used for the pentads used in the preprocessing to fully replicate your work before I try it with my own data.

Thanks. 

`pentads = pd.read_csv('/content/drive/MyDrive/School/M.S./Courses/Capstone/Colab/Data/CSVs/drought_variable_pentads.csv')
`

**Comment by anniebritton** [comment]
Of course! Attached below: 
[drought_variable_pentads.csv](https://github.com/user-attachments/files/17750820/drought_variable_pentads.csv)
